package testoflife

trait Shapes {
  protected val singleCell: String =
    """|.....
       |.....
       |..o..
       |.....
       |.....
    """.stripMargin

  protected val dualCell: String =
    """|.....
       |.....
       |..oo.
       |.....
       |.....
    """.stripMargin

  protected val triCell: String =
    """|.....
       |.....
       |.ooo.
       |.....
       |.....
    """.stripMargin

  protected val quadCell: String =
    """|.....
       |..oo.
       |..oo.
       |.....
       |.....
    """.stripMargin
}
